package com.earnplayapps.passportphoto;

import android.app.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.widget.*;import java.io.*;import java.util.*;

/** Pro batch processor: auto-frame first, validate the framed result, then export using the selected requirement. */
public class BatchActivity extends Activity{
 ArrayList<Uri> photos=new ArrayList<>();ArrayList<Requirement> reqs=new ArrayList<>();Spinner selector;TextView status;Button run;ProgressBar progress;volatile boolean cancelled=false;
 int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setMinHeight(dp(50));return x;}
 @Override public void onCreate(Bundle x){super.onCreate(x);if(!ProManager.isPro(this)){new AlertDialog.Builder(this).setTitle("Pro required").setMessage("Batch Processing ialah fungsi Pro RM19.90 Lifetime.").setPositiveButton("Pro",(d,w)->{startActivity(new Intent(this,PaymentActivity.class));finish();}).setNegativeButton("Back",(d,w)->finish()).show();return;}ArrayList<String> raw=getIntent().getStringArrayListExtra("uris");if(raw!=null)for(String s:raw)try{photos.add(Uri.parse(s));}catch(Exception ignored){}String id=getIntent().getStringExtra("requirement_id");for(Requirement r:MalaysiaRequirements.all())reqs.add(r);if(photos.isEmpty()||reqs.isEmpty()){showEmpty();return;}build(id);}
 void showEmpty(){new AlertDialog.Builder(this).setTitle("Batch Processing").setMessage("Tiada foto atau requirement tersedia.").setPositiveButton("Back",(d,w)->finish()).show();}
 void build(String lockedId){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(20));root.setBackgroundColor(0xfff5f7fb);TextView t=new TextView(this);t.setText("Passport Photo • Batch Processing");t.setTextSize(25);t.setTextColor(0xff17233d);root.addView(t);TextView n=new TextView(this);n.setText(photos.size()+" foto dipilih. Semua foto menggunakan satu requirement yang sama.");n.setTextSize(15);root.addView(n);selector=new Spinner(this);ArrayList<String> labels=new ArrayList<>();int selected=0;for(int i=0;i<reqs.size();i++){Requirement r=reqs.get(i);labels.add(r.purpose+" • "+r.size+" • "+r.background);if(r.id.equals(lockedId))selected=i;}selector.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,labels));selector.setSelection(selected);if(lockedId!=null&&!lockedId.isEmpty())selector.setEnabled(false);root.addView(selector);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(Math.max(1,photos.size()));progress.setProgress(0);root.addView(progress,new LinearLayout.LayoutParams(-1,dp(12)));status=new TextView(this);status.setText("Pilih requirement rasmi sebelum memproses.");status.setTextSize(14);root.addView(status);LinearLayout actions=new LinearLayout(this);run=b("PROCESS BATCH");run.setOnClickListener(v->process());actions.addView(run,new LinearLayout.LayoutParams(0,dp(52),2));Button cancel=b("Cancel");cancel.setOnClickListener(v->{cancelled=true;status.setText("Membatalkan…");});actions.addView(cancel,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(actions);Button back=b("Back");back.setOnClickListener(v->finish());root.addView(back);setContentView(root);}
 void process(){if(photos.isEmpty()){status.setText("Tiada foto untuk diproses.");return;}final Requirement r=reqs.get(selector.getSelectedItemPosition());if(r.widthMm<=0||r.heightMm<=0){new AlertDialog.Builder(this).setTitle("Ukuran tidak dinyatakan").setMessage("Sumber rasmi tidak memberikan ukuran fizikal. Batch tidak akan mereka ukuran. Gunakan Custom Size dengan ukuran sebenar daripada borang/institusi.").setPositiveButton("OK",null).show();return;}cancelled=false;run.setEnabled(false);progress.setProgress(0);status.setText("Processing 0 / "+photos.size()+"…");new Thread(()->{int ok=0,fail=0,done=0;StringBuilder errors=new StringBuilder();for(int i=0;i<photos.size();i++){if(cancelled)break;Bitmap src=null,out=null,sized=null;try{src=decode(photos.get(i));if(src==null)throw new IOException("read failed");out=PhotoEngine.autoCrop(src,r.widthMm,r.heightMm);if(out==null)throw new IOException("auto framing failed");ComplianceEngine.Report report=ComplianceEngine.check(out,r);boolean hasFail=false;for(ComplianceEngine.Issue issue:report.issues)if("FAIL".equals(issue.status)){hasFail=true;break;}if(hasFail){fail++;errors.append("Foto ").append(i+1).append(": tidak lulus selepas auto-frame\n");}else{sized=PhotoEngine.resizeForPrint(out,PhotoEngine.mmToPx(r.widthMm),PhotoEngine.mmToPx(r.heightMm));byte[] data=encodeForRequirement(sized,r);save(data,i+1,r);ok++;}}catch(Exception e){fail++;errors.append("Foto ").append(i+1).append(": ").append(e.getMessage()).append("\n");}finally{if(sized!=null&&sized!=out)sized.recycle();if(out!=null&&out!=src)out.recycle();if(src!=null&&!src.isRecycled())src.recycle();}done=i+1;final int d=done;runOnUiThread(()->{progress.setProgress(d);status.setText("Processing "+d+" / "+photos.size()+"…");});}final int f=fail,o=ok,d=done;runOnUiThread(()->{run.setEnabled(true);if(cancelled){new AlertDialog.Builder(this).setTitle("Batch dibatalkan").setMessage("Selesai: "+d+"\nBerjaya: "+o+"\nGagal: "+f).setPositiveButton("OK",null).show();status.setText("Batch dibatalkan selepas "+d+" foto.");}else{new AlertDialog.Builder(this).setTitle("Batch selesai").setMessage("Berjaya: "+o+"\nGagal / perlu pembetulan: "+f+(errors.length()>0?"\n\n"+errors:"" )).setPositiveButton("OK",null).show();status.setText("Batch selesai: "+o+" berjaya, "+f+" gagal.");}});}).start();}
 byte[] encodeForRequirement(Bitmap b,Requirement r)throws Exception{String fmt=r.format==null?"":r.format.toLowerCase(Locale.US);boolean png=fmt.contains("png")&&!fmt.contains("jpg");long limit=parseLimitBytes(r.maxFileSize);if(png){byte[] d=PhotoEngine.png(b);if(limit>0&&d.length>limit)throw new IOException("PNG output exceeds the official file-size maximum.");return d;}if(limit>0&&r.maxFileSize!=null&&r.maxFileSize.toLowerCase(Locale.US).contains("minimum")){byte[] d=PhotoEngine.jpeg(b,100);if(d.length<limit)throw new IOException("JPEG output is below the official minimum file size.");return d;}if(limit>0){for(int q=95;q>=30;q-=5){byte[] d=PhotoEngine.jpeg(b,q);if(d.length<=limit)return d;}throw new IOException("Unable to meet the official JPEG file-size maximum.");}return PhotoEngine.jpeg(b,95);}
 long parseLimitBytes(String rule){try{String x=rule==null?"":rule.toLowerCase(Locale.US).replace(',','.');String num=x.replaceAll("[^0-9.]","");if(num.isEmpty())return-1;double n=Double.parseDouble(num);if(x.contains("mb"))return(long)(n*1024d*1024d);if(x.contains("kb"))return(long)(n*1024d);}catch(Exception ignored){}return-1;}
 Bitmap decode(Uri u)throws Exception{BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;InputStream a=getContentResolver().openInputStream(u);if(a==null)throw new IOException("input unavailable");BitmapFactory.decodeStream(a,null,o);a.close();if(o.outWidth<=0||o.outHeight<=0)throw new IOException("invalid image");int s=1;while(Math.max(o.outWidth,o.outHeight)/(s*2)>2400)s*=2;o.inJustDecodeBounds=false;o.inSampleSize=s;o.inPreferredConfig=Bitmap.Config.ARGB_8888;InputStream in=getContentResolver().openInputStream(u);if(in==null)throw new IOException("input unavailable");Bitmap b=BitmapFactory.decodeStream(in,null,o);in.close();return b;}
 void save(byte[] data,int n,Requirement r)throws Exception{String fmt=r.format==null?"":r.format.toLowerCase(Locale.US);boolean png=fmt.contains("png")&&!fmt.contains("jpg");String ext=png?"png":"jpg";String name="PassportPhoto_Batch_"+n+"_"+System.currentTimeMillis()+"."+ext;ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,name);v.put(MediaStore.Images.Media.MIME_TYPE,png?"image/png":"image/jpeg");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Passport Photo");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(u==null)throw new IOException("MediaStore insert failed");try(OutputStream out=getContentResolver().openOutputStream(u)){if(out==null)throw new IOException("output failed");out.write(data);}}
}
