package com.earnplayapps.passportphoto;

import android.app.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.widget.*;import java.io.*;import java.util.*;

public class BatchActivity extends Activity{
 ArrayList<Uri> photos=new ArrayList<>();ArrayList<Requirement> reqs=new ArrayList<>();Spinner selector;TextView status;int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setMinHeight(dp(50));return x;}
 @Override public void onCreate(Bundle x){super.onCreate(x);if(!ProManager.isPro(this)){new AlertDialog.Builder(this).setTitle("Pro required").setMessage("Batch Processing ialah fungsi Pro RM19.90 Lifetime.").setPositiveButton("Pro",(d,w)->{startActivity(new Intent(this,PaymentActivity.class));finish();}).setNegativeButton("Back",(d,w)->finish()).show();return;}String[] raw=getIntent().getStringArrayExtra("uris");if(raw!=null)for(String s:raw)try{photos.add(Uri.parse(s));}catch(Exception ignored){}String id=getIntent().getStringExtra("requirement_id");for(Requirement r:MalaysiaRequirements.all())reqs.add(r);build(id);}
 void build(String lockedId){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(20));root.setBackgroundColor(0xfff5f7fb);TextView t=new TextView(this);t.setText("Passport Photo • Batch Processing");t.setTextSize(25);t.setTextColor(0xff17233d);root.addView(t);TextView n=new TextView(this);n.setText(photos.size()+" foto dipilih. Semua foto akan menggunakan satu requirement yang sama.");n.setTextSize(15);root.addView(n);selector=new Spinner(this);ArrayList<String> labels=new ArrayList<>();int selected=0;for(int i=0;i<reqs.size();i++){Requirement r=reqs.get(i);labels.add(r.purpose+" • "+r.size+" • "+r.background);if(r.id.equals(lockedId))selected=i;}selector.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,labels));selector.setSelection(selected);if(lockedId!=null&&!lockedId.isEmpty())selector.setEnabled(false);root.addView(selector);status=new TextView(this);status.setText("Pilih requirement rasmi sebelum memproses.");status.setTextSize(14);root.addView(status);Button run=b("PROCESS BATCH");run.setOnClickListener(v->process());root.addView(run);Button back=b("Back");back.setOnClickListener(v->finish());root.addView(back);setContentView(root);}
 void process(){if(photos.isEmpty()){status.setText("Tiada foto untuk diproses.");return;}final Requirement r=reqs.get(selector.getSelectedItemPosition());if(r.widthMm<=0||r.heightMm<=0){new AlertDialog.Builder(this).setTitle("Ukuran tidak dinyatakan").setMessage("Sumber rasmi untuk requirement ini tidak memberikan ukuran fizikal. Batch export tidak akan mereka ukuran. Gunakan Custom Size dengan ukuran sebenar daripada borang/institusi, kemudian proses foto.").setPositiveButton("OK",null).show();return;}status.setText("Processing 0 / "+photos.size()+"…");new Thread(()->{int ok=0,fail=0;StringBuilder errors=new StringBuilder();for(int i=0;i<photos.size();i++){try{Bitmap src=decode(photos.get(i));if(src==null)throw new IOException("read failed");ComplianceEngine.Report report=ComplianceEngine.check(src,r);boolean hasFail=false;for(ComplianceEngine.Issue issue:report.issues)if("FAIL".equals(issue.status)){hasFail=true;break;}if(hasFail){fail++;errors.append("Foto ").append(i+1).append(": tidak lulus checker\n");}else{Bitmap out=PhotoEngine.resizeForPrintMm(src,r.widthMm,r.heightMm);byte[] data=PhotoEngine.jpeg(out,95);save(data,i+1);if(out!=src)out.recycle();ok++;}src.recycle();}catch(Exception e){fail++;errors.append("Foto ").append(i+1).append(": ").append(e.getMessage()).append("\n");}final int done=i+1;runOnUiThread(()->status.setText("Processing "+done+" / "+photos.size()+"…"));}int f=fail,o=ok;runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Batch selesai").setMessage("Berjaya: "+o+"\nGagal / perlu pembetulan: "+f+(errors.length()>0?"\n\n"+errors:"" )).setPositiveButton("OK",null).show());}).start();}
 Bitmap decode(Uri u)throws Exception{BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;InputStream a=getContentResolver().openInputStream(u);if(a==null)throw new IOException("input unavailable");BitmapFactory.decodeStream(a,null,o);a.close();if(o.outWidth<=0||o.outHeight<=0)throw new IOException("invalid image");int s=1;while(Math.max(o.outWidth,o.outHeight)/(s*2)>2400)s*=2;o.inJustDecodeBounds=false;o.inSampleSize=s;o.inPreferredConfig=Bitmap.Config.ARGB_8888;InputStream in=getContentResolver().openInputStream(u);if(in==null)throw new IOException("input unavailable");Bitmap b=BitmapFactory.decodeStream(in,null,o);in.close();return b;}
 void save(byte[] data,int n)throws Exception{String name="PassportPhoto_Batch_"+n+"_"+System.currentTimeMillis()+".jpg";ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,name);v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Passport Photo");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(u==null)throw new IOException("MediaStore insert failed");try(OutputStream out=getContentResolver().openOutputStream(u)){if(out==null)throw new IOException("output failed");out.write(data);}}
}
