package com.earnplayapps.passportphoto;

import android.graphics.Bitmap;import android.graphics.Color;import java.util.*;
public final class ComplianceEngine{
 public static final class Issue{public final String title,detail,status;Issue(String t,String d,String s){title=t;detail=d;status=s;}}
 public static final class Report{public final List<Issue> issues;public final boolean pass;public final String summary;Report(List<Issue> i){issues=i;boolean blocked=false;for(Issue x:i)if("FAIL".equals(x.status)||"WARNING".equals(x.status))blocked=true;pass=!blocked;summary=pass?"PASS — READY TO EXPORT":"CHECK REQUIRED — FIX OR VERIFY PHOTO";}}
 private ComplianceEngine(){}
 public static Report check(Bitmap b,Requirement r){List<Issue> o=new ArrayList<>();if(b==null){o.add(new Issue("Photo","No photo loaded.","FAIL"));return new Report(o);}if(r==null){o.add(new Issue("Requirement","No requirement selected. Use a documented custom specification when the form or institution provides its own requirement.","WARNING"));return new Report(o);}FaceAnalyzer.Result f=FaceAnalyzer.analyze(b);if(!f.found)o.add(new Issue("Face","No clear face detected. Use a front-facing photo.","FAIL"));else if(f.count>1)o.add(new Issue("Multiple faces","More than one face detected. Select or crop the correct person.","FAIL"));else if(f.confidence<.70f)o.add(new Issue("Head angle","Face angle appears uncertain. Face the camera directly and verify the final crop.","WARNING"));else o.add(new Issue("Face","One face detected and approximately front-facing.","PASS"));
  if(r.widthMm>0&&r.heightMm>0){float rr=(float)r.widthMm/r.heightMm,ar=(float)b.getWidth()/b.getHeight();if(Math.abs(rr-ar)/rr<=.01f)o.add(new Issue("Aspect ratio",r.widthMm+" × "+r.heightMm+" mm ratio matches the selected requirement.","PASS"));else o.add(new Issue("Aspect ratio","Current image ratio does not match "+r.widthMm+" × "+r.heightMm+" mm. Crop using the selected requirement.","FAIL"));o.add(new Issue("Physical output","Export will generate the selected physical dimensions at 300 DPI.","INFO"));}else o.add(new Issue("Size","Official source does not specify an exact measurement. No dimension is assumed.","INFO"));
  if(r.pixelWidth>0&&r.pixelHeight>0){if(b.getWidth()==r.pixelWidth&&b.getHeight()==r.pixelHeight)o.add(new Issue("Pixel dimensions",r.pixelWidth+" × "+r.pixelHeight+" px matches the selected requirement.","PASS"));else o.add(new Issue("Pixel dimensions","Final output must be "+r.pixelWidth+" × "+r.pixelHeight+" px; export will resize to that exact output.","INFO"));}
  String bg=r.background==null?"":r.background.toLowerCase();if(bg.contains("tidak dinyatakan")||bg.contains("unspecified")||bg.trim().isEmpty())o.add(new Issue("Background","Background is not specified by this official source. No background rule is assumed.","INFO"));else if(bg.contains("putih")){int sample=0,white=0,sx=Math.max(1,b.getWidth()/20),sy=Math.max(1,b.getHeight()/20);for(int y=0;y<b.getHeight();y+=sy)for(int x=0;x<b.getWidth();x+=sx){int p=b.getPixel(x,y);sample++;if(Color.red(p)>235&&Color.green(p)>235&&Color.blue(p)>235)white++;}if(sample>0&&white/(float)sample<.35f)o.add(new Issue("Background sample","Large sampled areas are not white. Check or replace the background.","WARNING"));else o.add(new Issue("Background","Required white background appears plausible from sampling; verify shadows and edges visually.","INFO"));}else o.add(new Issue("Background","Required: "+r.background+". Sampling alone cannot prove official compliance; verify visually.","INFO"));
  if(b.getWidth()<600||b.getHeight()<600)o.add(new Issue("Resolution","Source image is relatively small. Use the highest-quality original available.","WARNING"));else o.add(new Issue("Resolution","Source resolution is adequate for editing.","PASS"));
  if(r.format!=null&&!r.format.trim().isEmpty()&&!r.format.toLowerCase().contains("tidak dinyatakan"))o.add(new Issue("File format","Required output format: "+r.format+". Final encoder applies the permitted format.","INFO"));if(r.maxFileSize!=null&&!r.maxFileSize.trim().isEmpty()&&!r.maxFileSize.toLowerCase().contains("tidak dinyatakan"))o.add(new Issue("File size","File-size rule: "+r.maxFileSize+". Final export validates the encoded file.","INFO"));if(r.faceRules!=null&&!r.faceRules.trim().isEmpty())o.add(new Issue("Official face rules",r.faceRules,"INFO"));return new Report(o);
 }
 public static boolean hasBlockingIssues(Report r){if(r==null)return true;for(Issue i:r.issues)if("FAIL".equals(i.status)||"WARNING".equals(i.status))return true;return false;}
}
