package com.earnplayapps.passportphoto;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity{
 static final int PICK=1001;String pendingRequirementId="";int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setMinHeight(dp(52));return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);home();}
 TextView title(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.rgb(23,35,61));t.setPadding(0,dp(10),0,dp(8));return t;}void base(LinearLayout r){r.setPadding(dp(18),dp(18),dp(18),dp(24));r.setBackgroundColor(Color.rgb(245,247,251));}
 void home(){ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);base(r);r.addView(title("Passport Photo",30));TextView sub=title("Malaysia • Photo preparation, compliance & print",15);sub.setTextColor(Color.rgb(91,100,117));r.addView(sub);r.addView(title("UTAMA",14));for(String x:new String[]{"Passport Malaysia","MyOnline Passport","Visa / MyVISA","Imigresen"}){Button q=btn(x);q.setOnClickListener(v->requirementsForMain(x));r.addView(q);}r.addView(title("DOKUMEN RASMI",14));for(String x:new String[]{"JPN","JPJ","PDRM","JKM / OKU","JHEV / ATM","JPA","KKM / Profesional","JAKIM / SPPIM","Agama Negeri","Bantuan / Zakat","PBT / Lesen / Permit","Agensi Kerajaan Lain"}){Button q=btn(x);q.setOnClickListener(v->requirements(x));r.addView(q);}r.addView(title("PENDIDIKAN",14));for(String x:new String[]{"Sekolah","Universiti / Kolej","Biasiswa"}){Button q=btn(x);q.setOnClickListener(v->generic(x));r.addView(q);}r.addView(title("KERJA",14));for(String x:new String[]{"Kerajaan / Penjawat Awam","Kerja / Resume","Profesional / Kad / Permit kerja"}){Button q=btn(x);q.setOnClickListener(v->generic(x));r.addView(q);}r.addView(title("TAMBAHAN",14));for(String x:new String[]{"Borang","Profile","Custom Size"}){Button q=btn(x);q.setOnClickListener(v->generic(x));r.addView(q);}r.addView(title("TOOLS",14));Button cam=btn("Camera");cam.setOnClickListener(v->startActivity(new Intent(this,CameraActivity.class)));r.addView(cam);Button gal=btn("Gallery");gal.setOnClickListener(v->pick(null));r.addView(gal);Button pro=btn("Pro • RM19.90 Lifetime");pro.setOnClickListener(v->startActivity(new Intent(this,PaymentActivity.class)));r.addView(pro);Button projects=btn("Projects / History");projects.setOnClickListener(v->projects());r.addView(projects);Button settings=btn("Settings • Privacy • Help • About");settings.setOnClickListener(v->infoScreen());r.addView(settings);setContentView(sv);}
 void requirementsForMain(String x){List<Requirement>a=new ArrayList<>();for(Requirement r:MalaysiaRequirements.all()){if(x.equals("Visa / MyVISA")&&r.purpose.toLowerCase().contains("myvisa"))a.add(r);else if(x.equals("Imigresen")&&r.agency.contains("Imigresen"))a.add(r);else if(x.equals("Passport Malaysia")&&r.purpose.toLowerCase().contains("pasport malaysia"))a.add(r);}if(a.isEmpty())generic(x);else listScreen(x,a);}
 void requirements(String cat){List<Requirement>a=new ArrayList<>();for(Requirement r:MalaysiaRequirements.all())if(r.category.equals(cat)||r.agency.toUpperCase().contains(cat.toUpperCase()))a.add(r);if(a.isEmpty())generic(cat);else listScreen(cat,a);}
 void listScreen(String cat,List<Requirement>ls){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);base(r);r.addView(title(cat,25));TextView note=title("Pilih urusan dahulu. Tiada ukuran akan dicipta jika sumber rasmi tidak menyatakannya.",14);note.setTextColor(Color.rgb(91,100,117));r.addView(note);for(Requirement x:ls){Button q=btn(x.purpose+"\n"+x.size+" • "+x.background+" • "+x.evidence);q.setOnClickListener(v->pick(x));r.addView(q);}Button back=btn("Back");back.setOnClickListener(v->home());r.addView(back);setContentView(r);}
 void generic(String name){new AlertDialog.Builder(this).setTitle(name).setMessage("Passport Photo menyediakan Photo Builder yang fleksibel untuk urusan ini. Pilih Custom Size jika borang/institusi tidak memberikan ukuran universal.").setPositiveButton("Choose Photo",(d,w)->pick(null)).setNegativeButton("Back",null).show();}
 void pick(Requirement req){pendingRequirementId=req==null?"":req.id;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK);}void pick(){pick(null);}
 void proScreen(){startActivity(new Intent(this,PaymentActivity.class));}
 void projects(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);base(r);r.addView(title("Projects / History",25));for(String s:ProjectStore.all(this))r.addView(title(s,15));Button clear=btn("Clear History");clear.setOnClickListener(v->{ProjectStore.clear(this);projects();});r.addView(clear);Button back=btn("Back");back.setOnClickListener(v->home());r.addView(back);setContentView(r);}
 void infoScreen(){new AlertDialog.Builder(this).setTitle("Passport Photo").setMessage("Malaysia only. Photos are processed locally where possible. No automatic photo upload. Final acceptance remains with the relevant authority. Requirement sources are shown per profile.\n\nPrivacy\nDelete saved projects/history from Projects.\n\nAdMaven is used only for Free mode when publisher configuration is supplied; Pro removes ads.").setPositiveButton("OK",null).show();}
 @Override protected void onActivityResult(int q,int res,Intent d){super.onActivityResult(q,res,d);if(q==PICK&&res==RESULT_OK&&d!=null&&d.getData()!=null){Intent i=new Intent(this,PhotoEditorActivity.class);i.setData(d.getData());if(!pendingRequirementId.isEmpty())i.putExtra("requirement_id",pendingRequirementId);startActivity(i);pendingRequirementId="";}}
}
