package com.earnplayapps.passportphoto;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 static final int PICK=1001;String pendingRequirementId="";int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setMinHeight(dp(52));return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);home();}
 TextView title(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.rgb(23,35,61));t.setPadding(0,dp(10),0,dp(8));return t;}void base(LinearLayout r){r.setPadding(dp(18),dp(18),dp(18),dp(24));r.setBackgroundColor(Color.rgb(245,247,251));}
 void home(){ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);base(r);r.addView(title("Passport Photo",30));TextView sub=title("Malaysia • Photo preparation, compliance & print",15);sub.setTextColor(Color.rgb(91,100,117));r.addView(sub);TextView status=title(ProManager.isPro(this)?"PRO • RM19.90 Lifetime • Ads off":"FREE • AdMaven",13);status.setTextColor(ProManager.isPro(this)?Color.rgb(25,110,75):Color.rgb(91,100,117));r.addView(status);r.addView(title("UTAMA",14));for(String x:new String[]{"Passport Malaysia","MyOnline Passport","Visa / MyVISA","Imigresen"}){Button q=btn(x);q.setOnClickListener(v->requirementsForMain(x));r.addView(q);}r.addView(title("DOKUMEN RASMI",14));for(String x:new String[]{"JPN","JPJ","PDRM","JKM / OKU","JHEV / ATM","JPA","KKM / Profesional","JAKIM / SPPIM","Agama Negeri","Bantuan / Zakat","PBT / Lesen / Permit","Agensi Kerajaan Lain"}){Button q=btn(x);q.setOnClickListener(v->requirements(x));r.addView(q);}r.addView(title("PENDIDIKAN",14));for(String x:new String[]{"Sekolah","Universiti / Kolej","Biasiswa"}){Button q=btn(x);q.setOnClickListener(v->generic(x));r.addView(q);}r.addView(title("KERJA",14));for(String x:new String[]{"Kerajaan / Penjawat Awam","Kerja / Resume","Profesional / Kad / Permit kerja"}){Button q=btn(x);q.setOnClickListener(v->generic(x));r.addView(q);}r.addView(title("TAMBAHAN",14));Button form=btn("Borang");form.setOnClickListener(v->customBuilder("Borang"));r.addView(form);Button profile=btn("Profile");profile.setOnClickListener(v->generic("Profile"));r.addView(profile);Button custom=btn("Custom Size");custom.setOnClickListener(v->customBuilder("Custom Size"));r.addView(custom);r.addView(title("TOOLS",14));Button cam=btn("Camera");cam.setOnClickListener(v->startActivity(new Intent(this,CameraActivity.class)));r.addView(cam);Button gal=btn("Gallery • Multiple Photos");gal.setOnClickListener(v->pick(null));r.addView(gal);Button pro=btn("Pro • RM19.90 Lifetime");pro.setOnClickListener(v->startActivity(new Intent(this,PaymentActivity.class)));r.addView(pro);Button projects=btn("Projects / History");projects.setOnClickListener(v->projects());r.addView(projects);Button settings=btn("Settings • Privacy • Help • About");settings.setOnClickListener(v->infoScreen());r.addView(settings);setContentView(sv);}
 void requirementsForMain(String x){if(x.equals("MyOnline Passport")){Requirement r=new Requirement("MY-MYONLINE-PASSPORT","UTAMA","Jabatan Imigresen Malaysia","MyOnline Passport","Pemohon Malaysia","passport",1,0,0,"Passport photo / ukuran fizikal tidak dinyatakan pada pengesahan muat naik","Putih","Memandang tepat; mata terbuka; mulut tertutup; rambut tidak melindungi wajah; dahi tidak ditutup sepenuhnya; pakaian gelap menutupi bahu/dada; tiada cermin mata/kanta lekap berwarna; tiada aksesori kepala; tiada cahaya flash pada dahi","JPG/format sistem","Tidak dinyatakan","OFFICIAL_EXPLICIT","ACTIVE","https://imigresen-online.imi.gov.my/eservices/myPasport");listScreen(x,Collections.singletonList(r));return;}List<Requirement>a=new ArrayList<>();for(Requirement r:MalaysiaRequirements.all()){String p=r.purpose.toLowerCase();if(x.equals("Visa / MyVISA")&&p.contains("myvisa"))a.add(r);else if(x.equals("Imigresen")&&r.agency.toLowerCase().contains("imigresen"))a.add(r);else if(x.equals("Passport Malaysia")&&p.contains("pasport malaysia"))a.add(r);}if(a.isEmpty())generic(x);else listScreen(x,a);}
 void requirements(String cat){List<Requirement>a=new ArrayList<>();for(Requirement r:MalaysiaRequirements.all())if(r.category.equals(cat)||r.agency.toUpperCase().contains(cat.toUpperCase()))a.add(r);if(a.isEmpty())generic(cat);else listScreen(cat,a);}
 void listScreen(String cat,List<Requirement>ls){ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);base(r);r.addView(title(cat,25));TextView note=title("Pilih urusan dahulu. Tekan satu urusan untuk lihat syarat dan sumber rasmi. Tiada ukuran akan dicipta jika sumber rasmi tidak menyatakannya.",14);note.setTextColor(Color.rgb(91,100,117));r.addView(note);for(Requirement x:ls){Button q=btn(x.purpose+"\n"+x.size+" • "+x.background+" • "+x.evidence);q.setOnClickListener(v->requirementDetail(x));r.addView(q);}Button custom=btn("Custom Size / Form Requirement");custom.setOnClickListener(v->customBuilder(cat));r.addView(custom);Button back=btn("Back");back.setOnClickListener(v->home());r.addView(back);sv.addView(r);setContentView(sv);}
 void requirementDetail(Requirement x){String msg="Agency: "+x.agency+"\nState: "+x.state+"\nInstitution: "+x.institution+"\nPurpose: "+x.purpose+"\nApplicant: "+x.applicant+"\nPhoto role: "+x.photoRole+"\nQuantity: "+x.quantity+"\nSize: "+x.size+"\nBackground: "+x.background+"\nFace rules: "+x.faceRules+"\nFormat: "+x.format+"\nMax file size: "+x.maxFileSize+"\nEvidence: "+x.evidence+"\nStatus: "+x.status+"\nVerified: "+x.verifiedDate+"\n\nOfficial source:\n"+x.source;new AlertDialog.Builder(this).setTitle(x.purpose).setMessage(msg).setPositiveButton("Use Requirement",(d,w)->pick(x)).setNeutralButton("Open Official Source",(d,w)->{try{startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse(x.source)));}catch(Exception e){Toast.makeText(this,"Source tidak dapat dibuka.",Toast.LENGTH_SHORT).show();}}).setNegativeButton("Back",null).show();}
 void generic(String name){new AlertDialog.Builder(this).setTitle(name).setMessage("Tiada ukuran universal rasmi dimasukkan untuk kategori ini. Jangan anggap passport-size sebagai ukuran tertentu. Jika borang/institusi memberi ukuran sendiri, gunakan Custom Size.").setPositiveButton("Custom Size",(d,w)->customBuilder(name)).setNeutralButton("Choose Photo",(d,w)->pick(null)).setNegativeButton("Back",null).show();}
 void customBuilder(String name){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(4),0,dp(4),0);EditText width=new EditText(this);width.setHint("Width (mm)");width.setInputType(2);l.addView(width);EditText height=new EditText(this);height.setHint("Height (mm)");height.setInputType(2);l.addView(height);Spinner bg=new Spinner(this);String[] opts={"Tidak dinyatakan","Putih","Biru","Kelabu muda"};bg.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,opts));l.addView(bg);new AlertDialog.Builder(this).setTitle(name+" • Custom Builder").setMessage("Masukkan ukuran tepat daripada borang/institusi. Nilai ini bukan tuntutan rasmi Passport Photo.").setView(l).setPositiveButton("Choose Photo",(d,w)->{try{int wm=Integer.parseInt(width.getText().toString().trim()),hm=Integer.parseInt(height.getText().toString().trim());if(wm<=0||hm<=0)throw new Exception();Intent i=new Intent(this,PhotoEditorActivity.class);i.putExtra("custom_width_mm",wm);i.putExtra("custom_height_mm",hm);i.putExtra("custom_background",bg.getSelectedItem().toString());startActivity(i);}catch(Exception e){Toast.makeText(this,"Masukkan width dan height dalam mm.",Toast.LENGTH_LONG).show();}}).setNegativeButton("Cancel",null).show();}
 void pick(Requirement req){pendingRequirementId=req==null?"":req.id;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK);}void pick(){pick(null);}
 void projects(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);base(r);r.addView(title("Projects / History",25));List<String> all=ProjectStore.all(this);if(all.isEmpty())r.addView(title("Belum ada export.",15));else for(String s:all)r.addView(title(s,15));Button clear=btn("Clear History");clear.setOnClickListener(v->{ProjectStore.clear(this);projects();});r.addView(clear);Button back=btn("Back");back.setOnClickListener(v->home());r.addView(back);setContentView(r);}
 void infoScreen(){new AlertDialog.Builder(this).setTitle("Passport Photo").setMessage("Malaysia only. Photos are processed locally where possible. No automatic photo upload. Final acceptance remains with the relevant authority.\n\nPrivacy\nDelete saved projects/history from Projects.\n\nAdMaven integration is currently held while the core photo system is completed. Pro remains RM19.90 Lifetime.").setPositiveButton("OK",null).show();}
 @Override protected void onActivityResult(int q,int res,Intent d){super.onActivityResult(q,res,d);if(q==PICK&&res==RESULT_OK&&d!=null){if(d.getClipData()!=null&&d.getClipData().getItemCount()>0){int n=d.getClipData().getItemCount();Toast.makeText(this,"Dipilih "+n+" foto. Batch processing akan menggunakan requirement yang sama apabila fungsi batch diaktifkan.",Toast.LENGTH_LONG).show();}else if(d.getData()!=null){Intent i=new Intent(this,PhotoEditorActivity.class);i.setData(d.getData());if(!pendingRequirementId.isEmpty())i.putExtra("requirement_id",pendingRequirementId);startActivity(i);}pendingRequirementId="";}}
}
