package com.earnplayapps.passportphoto;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
    private static final int PICK=1001;
    private String pendingRequirementId="";
    private final int BG=Color.rgb(246,249,253), NAVY=Color.rgb(20,42,78), BLUE=Color.rgb(48,112,224), MUTED=Color.rgb(92,108,132), LINE=Color.rgb(222,230,242), PALE=Color.rgb(239,246,255);
    int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
    TextView text(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);return t;}
    GradientDrawable bg(int fill,int stroke,float r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp((int)r));if(stroke!=0)g.setStroke(dp(1),stroke);return g;}
    LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    TextView title(String s){TextView t=text(s,15,NAVY);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    TextView section(String s){TextView t=text(s,14,NAVY);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setLetterSpacing(.06f);t.setPadding(dp(2),dp(20),0,dp(10));return t;}
    Button action(String s){Button b=new Button(this);b.setText(s);b.setTextSize(13);b.setTextColor(NAVY);b.setAllCaps(false);b.setMinHeight(dp(48));b.setPadding(dp(10),0,dp(10),0);b.setBackground(bg(Color.WHITE,LINE,16));b.setElevation(dp(2));return b;}
    View gap(int w,int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(w,h));return s;}

    @Override public void onCreate(Bundle state){super.onCreate(state);showHome();}

    void showHome(){
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout root=col();root.setPadding(dp(16),dp(14),dp(16),dp(20));root.setBackgroundColor(BG);
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);
        LinearLayout brand=col();TextView b=text("Passport Photo",25,NAVY);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);brand.addView(b);brand.addView(text("Malaysia • Photo preparation & compliance",11,MUTED));head.addView(brand,new LinearLayout.LayoutParams(0,-2,1));
        Button pro=action(ProManager.isPro(this)?"PRO":"PRO");pro.setTextColor(BLUE);pro.setOnClickListener(v->startActivity(new Intent(this,PaymentActivity.class)));head.addView(pro,new LinearLayout.LayoutParams(dp(62),dp(44)));root.addView(head);
        LinearLayout status=col();status.setPadding(dp(14),dp(10),dp(14),dp(10));status.setBackground(bg(ProManager.isPro(this)?Color.rgb(232,247,240):PALE,0,15));TextView st=text(ProManager.isPro(this)?"PRO • RM19.90 Lifetime • No ads":"FREE • Core photo tools",12,ProManager.isPro(this)?Color.rgb(25,119,74):BLUE);st.setTypeface(Typeface.DEFAULT,Typeface.BOLD);status.addView(st);root.addView(status,new LinearLayout.LayoutParams(-1,dp(42)));
        root.addView(gap(1,dp(12)));root.addView(hero());
        root.addView(section("URUSAN UTAMA"));root.addView(featureRow("MyOnline Passport","Foto untuk urusan passport dalam talian", "PASSPORT"));root.addView(gap(1,dp(8)));root.addView(featureRow("Visa / MyVISA","VDR / VTR dan keperluan foto berkaitan", "MYVISA"));root.addView(gap(1,dp(8)));root.addView(featureRow("Imigresen","Pas dan dokumen perjalanan Malaysia", "IMIGRESEN"));
        root.addView(section("DOKUMEN RASMI"));root.addView(grid(new String[]{"JPN","JPJ","PDRM","JKM / OKU","JHEV / ATM","JPA","KKM / Profesional","JAKIM / SPPIM","Agama Negeri","Bantuan / Zakat","PBT / Lesen / Permit","Agensi Kerajaan Lain"}));
        root.addView(section("PENDIDIKAN & KERJA"));root.addView(grid(new String[]{"Sekolah","Universiti / Kolej","Biasiswa","Kerajaan / Penjawat Awam","Kerja / Resume","Profesional / Kad / Permit kerja"}));
        root.addView(section("TAMBAHAN"));root.addView(grid(new String[]{"Borang","Profile","Custom Size"}));
        root.addView(section("ALAT & PROJEK"));root.addView(toolGrid());
        TextView note=text("Pemprosesan lokal apabila boleh. Foto tidak dimuat naik secara automatik.\nPenerimaan akhir tetap tertakluk kepada agensi atau institusi berkaitan.",10,MUTED);note.setGravity(Gravity.CENTER);note.setPadding(dp(8),dp(20),dp(8),0);root.addView(note);
        root.addView(bottomNav());scroll.addView(root);setContentView(scroll);
    }

    View hero(){
        LinearLayout card=col();card.setPadding(dp(18),dp(18),dp(18),dp(16));card.setBackground(bg(Color.WHITE,Color.rgb(201,220,247),26));card.setElevation(dp(5));
        TextView tag=text("FUNGSI UTAMA",10,Color.WHITE);tag.setGravity(Gravity.CENTER);tag.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tag.setBackground(bg(BLUE,0,30));card.addView(tag,new LinearLayout.LayoutParams(dp(105),dp(28)));
        TextView h=text("Passport Malaysia",25,NAVY);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setPadding(0,dp(11),0,dp(3));card.addView(h);TextView d=text("Pilih foto, ikut panduan, semak keperluan dan sediakan output untuk digital atau cetakan.",13,MUTED);d.setLineSpacing(0,1.08f);card.addView(d);
        LinearLayout primary=col();primary.setPadding(0,dp(14),0,0);Button create=action("CREATE PHOTO");create.setTextColor(Color.WHITE);create.setTypeface(Typeface.DEFAULT,Typeface.BOLD);create.setBackground(bg(BLUE,0,15));create.setOnClickListener(v->requirementsForMain("Passport Malaysia"));primary.addView(create);card.addView(primary);
        LinearLayout quick=new LinearLayout(this);quick.setPadding(0,dp(10),0,0);quick.addView(quick("CAMERA","Ambil Foto",v->startActivity(new Intent(this,CameraActivity.class))),new LinearLayout.LayoutParams(0,dp(70),1));quick.addView(gap(dp(7),1));quick.addView(quick("GALLERY","Pilih Galeri",v->pick(null)),new LinearLayout.LayoutParams(0,dp(70),1));quick.addView(gap(dp(7),1));quick.addView(quick("TEMPLATE","Preset",v->requirementsForMain("Passport Malaysia")),new LinearLayout.LayoutParams(0,dp(70),1));card.addView(quick);return card;
    }
    View quick(String code,String name,View.OnClickListener click){LinearLayout x=col();x.setGravity(Gravity.CENTER);x.setPadding(dp(4),dp(5),dp(4),dp(5));x.setBackground(bg(PALE,LINE,15));x.setOnClickListener(click);TextView c=text(code,9,BLUE);c.setGravity(Gravity.CENTER);c.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(c);TextView n=text(name,11,NAVY);n.setGravity(Gravity.CENTER);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(n);return x;}
    View featureRow(String name,String sub,String code){LinearLayout x=col();x.setPadding(dp(15),dp(13),dp(15),dp(13));x.setBackground(bg(Color.WHITE,LINE,19));x.setElevation(dp(2));x.setOnClickListener(v->requirementsForMain(name));LinearLayout row=new LinearLayout(this);TextView c=text(code,10,BLUE);c.setTypeface(Typeface.DEFAULT,Typeface.BOLD);row.addView(c,new LinearLayout.LayoutParams(dp(82),-2));TextView n=title(name);row.addView(n,new LinearLayout.LayoutParams(0,-2,1));TextView a=text("›",28,BLUE);a.setGravity(Gravity.CENTER);row.addView(a,new LinearLayout.LayoutParams(dp(28),dp(32)));x.addView(row);x.addView(text(sub,11,MUTED));return x;}
    View grid(String[] names){LinearLayout out=col();for(int i=0;i<names.length;i+=2){LinearLayout r=new LinearLayout(this);for(int j=0;j<2;j++){int k=i+j;if(k<names.length){String n=names[k];Button b=action(n);b.setGravity(Gravity.CENTER);b.setTextSize(12);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setOnClickListener(v->openCategory(n));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(58),1);p.setMargins(j==0?0:dp(5),0,j==1?0:dp(5),dp(7));r.addView(b,p);}else r.addView(gap(0,dp(58)),new LinearLayout.LayoutParams(0,dp(58),1));}out.addView(r);}return out;}
    View toolGrid(){LinearLayout r=new LinearLayout(this);String[] a={"KAMERA","GALERI","PROJEK","PRO"};for(int i=0;i<a.length;i++){String n=a[i];Button b=action(n);b.setTextSize(11);b.setOnClickListener(v->{if(n.equals("KAMERA"))startActivity(new Intent(this,CameraActivity.class));else if(n.equals("GALERI"))pick(null);else if(n.equals("PROJEK"))projects();else startActivity(new Intent(this,PaymentActivity.class));});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(62),1);p.setMargins(i==0?0:dp(4),0,i==a.length-1?0:dp(4),0);r.addView(b,p);}return r;}
    View bottomNav(){LinearLayout nav=new LinearLayout(this);nav.setPadding(0,dp(14),0,0);String[] a={"HOME","CATEGORIES","CAMERA","PROJECTS","SETTINGS"};for(String n:a){Button b=action(n);b.setTextSize(9);b.setBackground(bg(Color.WHITE,LINE,14));b.setOnClickListener(v->{if(n.equals("HOME"))showHome();else if(n.equals("CATEGORIES"))categoriesScreen();else if(n.equals("CAMERA"))startActivity(new Intent(this,CameraActivity.class));else if(n.equals("PROJECTS"))projects();else infoScreen();});nav.addView(b,new LinearLayout.LayoutParams(0,dp(48),1));}return nav;}

    void openCategory(String n){if(n.equals("Borang")||n.equals("Custom Size"))customBuilder(n);else if(n.equals("Profile")||n.equals("Sekolah")||n.equals("Universiti / Kolej")||n.equals("Biasiswa")||n.equals("Kerajaan / Penjawat Awam")||n.equals("Kerja / Resume")||n.equals("Profesional / Kad / Permit kerja"))generic(n);else requirements(n);}
    void categoriesScreen(){ScrollView s=new ScrollView(this);LinearLayout r=col();r.setPadding(dp(16),dp(18),dp(16),dp(24));r.setBackgroundColor(BG);TextView h=text("Kategori",26,NAVY);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(h);r.addView(text("Pilih urusan Malaysia mengikut agensi, pendidikan, kerja atau kegunaan tambahan.",12,MUTED));r.addView(section("DOKUMEN RASMI"));r.addView(grid(new String[]{"JPN","JPJ","PDRM","JKM / OKU","JHEV / ATM","JPA","KKM / Profesional","JAKIM / SPPIM","Agama Negeri","Bantuan / Zakat","PBT / Lesen / Permit","Agensi Kerajaan Lain"}));r.addView(section("PENDIDIKAN"));r.addView(grid(new String[]{"Sekolah","Universiti / Kolej","Biasiswa"}));r.addView(section("KERJA"));r.addView(grid(new String[]{"Kerajaan / Penjawat Awam","Kerja / Resume","Profesional / Kad / Permit kerja"}));r.addView(section("TAMBAHAN"));r.addView(grid(new String[]{"Borang","Profile","Custom Size"}));Button back=action("Kembali ke Home");back.setOnClickListener(v->showHome());r.addView(back);s.addView(r);setContentView(s);}

    void requirementsForMain(String x){ArrayList<Requirement>a=new ArrayList<>();for(Requirement q:MalaysiaRequirements.all()){String p=q.purpose.toLowerCase();if(x.equals("Passport Malaysia")&&p.contains("pasport malaysia"))a.add(q);else if(x.equals("MyOnline Passport")&&p.contains("passport")&&q.agency.toLowerCase().contains("imigresen"))a.add(q);else if(x.equals("Visa / MyVISA")&&p.contains("myvisa"))a.add(q);else if(x.equals("Imigresen")&&q.agency.toLowerCase().contains("imigresen"))a.add(q);}if(a.isEmpty())generic(x);else listScreen(x,a);}
    void requirements(String cat){ArrayList<Requirement>a=new ArrayList<>();for(Requirement q:MalaysiaRequirements.all())if(q.category.equals(cat)||q.agency.toLowerCase().contains(cat.toLowerCase()))a.add(q);if(a.isEmpty())generic(cat);else listScreen(cat,a);}
    void listScreen(String cat,ArrayList<Requirement> list){ScrollView s=new ScrollView(this);LinearLayout r=col();r.setPadding(dp(16),dp(18),dp(16),dp(24));r.setBackgroundColor(BG);TextView h=text(cat,24,NAVY);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(h);r.addView(text("Keperluan dipaparkan mengikut sumber dan status pengesahan. Tiada ukuran direka jika sumber rasmi tidak menyatakannya.",11,MUTED));for(Requirement q:list){Button b=action(q.purpose+"\n"+q.size+" • "+q.background+" • "+q.evidence);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setOnClickListener(v->detail(q));r.addView(b,new LinearLayout.LayoutParams(-1,dp(70)));((LinearLayout.LayoutParams)b.getLayoutParams()).setMargins(0,dp(8),0,0);}Button back=action("Kembali");back.setOnClickListener(v->showHome());r.addView(back,new LinearLayout.LayoutParams(-1,dp(50)));s.addView(r);setContentView(s);}
    void detail(Requirement q){String m="Agensi: "+q.agency+"\nNegeri: "+q.state+"\nInstitusi: "+q.institution+"\nUrusan: "+q.purpose+"\nPemohon: "+q.applicant+"\nPeranan foto: "+q.photoRole+"\nKuantiti: "+q.quantity+"\nSaiz: "+q.size+"\nLatar: "+q.background+"\nPeraturan wajah: "+q.faceRules+"\nFormat: "+q.format+"\nSaiz fail maksimum: "+q.maxFileSize+"\nBukti: "+q.evidence+"\nStatus: "+q.status+"\nDisahkan: "+q.verifiedDate+"\n\nSumber rasmi:\n"+q.source;new AlertDialog.Builder(this).setTitle(q.purpose).setMessage(m).setPositiveButton("Guna Requirement",(d,w)->pick(q)).setNeutralButton("Sumber Rasmi",(d,w)->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(q.source)));}catch(Exception e){Toast.makeText(this,"Sumber tidak dapat dibuka.",Toast.LENGTH_SHORT).show();}}).setNegativeButton("Tutup",null).show();}
    void generic(String n){new AlertDialog.Builder(this).setTitle(n).setMessage("Tiada ukuran universal rasmi yang disahkan untuk kategori ini. Gunakan ukuran sebenar daripada borang atau institusi melalui Custom Size. Jangan anggap semua 'passport-size' mempunyai ukuran yang sama.").setPositiveButton("Custom Size",(d,w)->customBuilder(n)).setNeutralButton("Pilih Foto",(d,w)->pick(null)).setNegativeButton("Tutup",null).show();}
    void customBuilder(String n){LinearLayout l=col();EditText w=new EditText(this);w.setHint("Width (mm)");w.setInputType(2);l.addView(w);EditText h=new EditText(this);h.setHint("Height (mm)");h.setInputType(2);l.addView(h);Spinner sp=new Spinner(this);String[] bs={"Tidak dinyatakan","Putih","Biru","Kelabu muda"};sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,bs));l.addView(sp);new AlertDialog.Builder(this).setTitle(n+" • Custom Size").setMessage("Masukkan ukuran yang diberikan oleh borang atau institusi.").setView(l).setPositiveButton("Pilih Foto",(d,x)->{try{int wm=Integer.parseInt(w.getText().toString().trim()),hm=Integer.parseInt(h.getText().toString().trim());if(wm<1||hm<1)throw new Exception();Intent i=new Intent(this,PhotoEditorActivity.class);i.putExtra("custom_width_mm",wm);i.putExtra("custom_height_mm",hm);i.putExtra("custom_background",sp.getSelectedItem().toString());startActivity(i);}catch(Exception e){Toast.makeText(this,"Masukkan width dan height yang sah.",Toast.LENGTH_LONG).show();}}).setNegativeButton("Batal",null).show();}
    void pick(Requirement q){pendingRequirementId=q==null?"":q.id;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req!=PICK||result!=RESULT_OK||data==null)return;Uri u=data.getData();if(u==null&&data.getClipData()!=null&&data.getClipData().getItemCount()>0)u=data.getClipData().getItemAt(0).getUri();if(u==null){Toast.makeText(this,"Foto tidak dipilih.",Toast.LENGTH_SHORT).show();return;}try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}Intent next=new Intent(this,PhotoEditorActivity.class);next.setData(u);if(!pendingRequirementId.isEmpty())next.putExtra("requirement_id",pendingRequirementId);startActivity(next);}
    void projects(){ArrayList<String> a=ProjectStore.all(this);StringBuilder m=new StringBuilder();if(a.isEmpty())m.append("Belum ada projek disimpan.");else for(String x:a)m.append("• ").append(x).append("\n");new AlertDialog.Builder(this).setTitle("Projects").setMessage(m.toString()).setPositiveButton("Kembali",null).setNeutralButton("Clear History",(d,w)->{ProjectStore.clear(this);Toast.makeText(this,"History dibersihkan.",Toast.LENGTH_SHORT).show();}).show();}
    void infoScreen(){new AlertDialog.Builder(this).setTitle("Passport Photo").setMessage("Malaysia-only photo preparation app\n\nPemprosesan foto dibuat secara lokal apabila boleh. Keperluan rasmi dipaparkan bersama status dan sumber apabila tersedia.\n\nPro: RM19.90 Lifetime • 1 device\n\nInstallation ID: "+Settings.Secure.getString(getContentResolver(),Settings.Secure.ANDROID_ID)).setPositiveButton("Tutup",null).setNeutralButton("Pro",(d,w)->startActivity(new Intent(this,PaymentActivity.class))).show();}
}
