package com.earnplayapps.passportphoto;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import android.print.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;

/** Focused Passport Photo home: select an official profile, photo, then automatic preparation. */
public class PassportHomeActivity extends Activity {
  static final int CAM=91,GAL=92; LinearLayout root; ImageView image; TextView status; Bitmap source,result; Requirement req;
  final int BG=0xfff5f9fe,NAVY=0xff173b69,BLUE=0xff315bce,MUTED=0xff65758d,LINE=0xffdbe6f5;
  int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} TextView t(String s,float z,int c){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);x.setPadding(dp(14),dp(8),dp(14),dp(8));return x;}
  GradientDrawable box(int fill,int stroke,int r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));if(stroke!=0)g.setStroke(dp(1),stroke);return g;}
  Button b(String s){Button x=new Button(this);x.setText(s);x.setTextSize(14);x.setTextColor(NAVY);x.setAllCaps(false);x.setMinHeight(dp(48));x.setBackground(box(Color.WHITE,LINE,16));return x;}
  @Override public void onCreate(Bundle x){super.onCreate(x);getWindow().setStatusBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);home();}
  void home(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(12));root.setBackgroundColor(BG);
    TextView h=t("Passport Photo",28,NAVY);h.setTypeface(null,1);root.addView(h,new LinearLayout.LayoutParams(-1,dp(44)));root.addView(t("Buat gambar passport dengan telefon",14,MUTED),new LinearLayout.LayoutParams(-1,dp(34)));
    TextView q=t("Pilih jenis gambar",18,NAVY);q.setTypeface(null,1);root.addView(q,new LinearLayout.LayoutParams(-1,dp(48)));
    ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
    for(Requirement r:passportRequirements()){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(5),dp(5),dp(5),dp(5));c.setBackground(box(Color.WHITE,LINE,18));TextView n=t(r.purpose,16,NAVY);n.setTypeface(null,1);c.addView(n);c.addView(t(r.size+"  •  Latar: "+r.background+"\n"+r.faceRules,11,MUTED));Button go=b("Pilih & teruskan");c.addView(go);go.setOnClickListener(v->select(r));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(132));cp.setMargins(0,0,0,dp(10));list.addView(c,cp);}
    LinearLayout foot=new LinearLayout(this);Button pr=b("Privasi"),tm=b("Terma");pr.setOnClickListener(v->privacy());tm.setOnClickListener(v->terms());foot.addView(pr,new LinearLayout.LayoutParams(0,dp(48),1));foot.addView(tm,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(foot);setContentView(root); }
  List<Requirement> passportRequirements(){List<Requirement>a=new ArrayList<>();for(Requirement r:MalaysiaRequirements.all()){String s=r.purpose.toLowerCase();if(s.contains("pasport malaysia")||s.contains("menyeberang sempadan malaysia")||s.contains("pas sempadan malaysia")||s.contains("dokumen perjalanan terhad")||s.contains("certificate of identity")||s.contains("surat akuan pengenalan")||s.contains("sijil perakuan cemas")||s.contains("pas pelajar")||s.contains("myvisa"))a.add(r);}return a;}
  void select(Requirement r){req=r; if(req.widthMm==0){new AlertDialog.Builder(this).setTitle(req.purpose).setMessage("Sumber rasmi belum memberikan ukuran foto yang cukup untuk automasi ukuran. App tidak akan mereka ukuran sendiri. Sila rujuk borang rasmi sebelum menggunakan output.").setPositiveButton("Faham",null).show();return;}input();}
  void input(){root.removeAllViews();TextView h=t(req.purpose,20,NAVY);h.setTypeface(null,1);root.addView(h,new LinearLayout.LayoutParams(-1,dp(54)));root.addView(t("Spesifikasi rasmi dimuatkan automatik: "+req.size+" • "+req.background,12,MUTED),new LinearLayout.LayoutParams(-1,dp(52)));
    LinearLayout a=new LinearLayout(this);Button c=b("Ambil Gambar"),g=b("Pilih Dari Galeri");a.addView(c,new LinearLayout.LayoutParams(0,dp(52),1));a.addView(g,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(a);c.setOnClickListener(v->camera());g.setOnClickListener(v->gallery());
    image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_INSIDE);image.setBackground(box(Color.WHITE,LINE,20));root.addView(image,new LinearLayout.LayoutParams(-1,0,1));status=t("Belum ada gambar",13,MUTED);status.setGravity(Gravity.CENTER);root.addView(status,new LinearLayout.LayoutParams(-1,dp(48)));
    LinearLayout nav=new LinearLayout(this);Button back=b("Kembali"),save=b("Simpan"),print=b("Print");nav.addView(back,new LinearLayout.LayoutParams(0,dp(52),1));nav.addView(save,new LinearLayout.LayoutParams(0,dp(52),1));nav.addView(print,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(nav);back.setOnClickListener(v->home());save.setOnClickListener(v->save());print.setOnClickListener(v->print());}
  void camera(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},CAM);return;}try{File f=new File(getCacheDir(),"passport_camera.jpg");f.delete();StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder().build());Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,Uri.fromFile(f));startActivityForResult(i,CAM);}catch(Exception e){toast("Kamera tidak dapat dibuka");}}
  void gallery(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,GAL);}
  @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK)return;try{if(r==GAL){InputStream in=getContentResolver().openInputStream(d.getData());source=BitmapFactory.decodeStream(in);in.close();}else source=BitmapFactory.decodeFile(new File(getCacheDir(),"passport_camera.jpg").getAbsolutePath());if(source==null)throw new Exception();status.setText("Memproses automatik…");new Handler().postDelayed(()->{result=process(source,req);image.setImageBitmap(result);status.setText("Siap — semak preview sebelum simpan atau print.");},120);}catch(Exception e){toast("Gambar tidak dapat dibaca");}}
  Bitmap process(Bitmap s,Requirement r){FaceAnalyzer.Result f=FaceAnalyzer.analyze(s);int w=Math.round(r.widthMm*300/25.4f),h=Math.round(r.heightMm*300/25.4f);float ratio=w/(float)h;int sw=s.getWidth(),sh=s.getHeight(),cw=sw,ch=Math.round(sw/ratio);if(ch>sh){ch=sh;cw=Math.round(sh*ratio);}float cx=f.found?f.midX:sw/2f,cy=f.found?f.midY:sh*.45f;int l=Math.max(0,Math.min(sw-cw,Math.round(cx-cw/2)));int top=Math.max(0,Math.min(sh-ch,Math.round(cy-ch*.43f)));Bitmap crop=Bitmap.createBitmap(s,l,top,cw,ch);Bitmap out=Bitmap.createScaledBitmap(crop,w,h,true);return floodBackground(out,r.background);}
  Bitmap floodBackground(Bitmap in,String bg){String low=bg.toLowerCase();int target=low.contains("biru")&&!low.contains("putih")?0xffdbe9f8:0xffffffff;Bitmap o=in.copy(Bitmap.Config.ARGB_8888,true);int w=o.getWidth(),h=o.getHeight();int[] p=new int[w*h];o.getPixels(p,0,w,0,0,w,h);boolean[] seen=new boolean[p.length];ArrayDeque<Integer>q=new ArrayDeque<>();int[] starts={0,w-1,(h-1)*w,w*h-1};for(int z:starts){q.add(z);seen[z]=true;}int base=p[0],br=Color.red(base),bgc=Color.green(base),bb=Color.blue(base);while(!q.isEmpty()){int i=q.remove(),col=p[i];if(Math.abs(Color.red(col)-br)+Math.abs(Color.green(col)-bgc)+Math.abs(Color.blue(col)-bb)>80)continue;p[i]=target;int x=i%w,y=i/w;int[] ds={1,-1,w,-w};for(int d:ds){int n=i+d;if(n<0||n>=p.length||(d==1&&x==w-1)||(d==-1&&x==0)||(d==w&&y==h-1)||(d==-w&&y==0)||seen[n])continue;seen[n]=true;q.add(n);}}o.setPixels(p,0,w,0,0,w,h);return o;}
  void save(){if(result==null){toast("Masukkan gambar dahulu");return;}try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"PassportPhoto_"+System.currentTimeMillis()+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Passport Photo");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);OutputStream o=getContentResolver().openOutputStream(u);result.compress(Bitmap.CompressFormat.JPEG,95,o);o.close();toast("Disimpan dalam Pictures/Passport Photo");}catch(Exception e){toast("Gagal menyimpan");}}
  void print(){if(result==null){toast("Masukkan gambar dahulu");return;}PrintManager pm=(PrintManager)getSystemService(PRINT_SERVICE);pm.print("Passport Photo",new PrintDocumentAdapter(){public void onLayout(PrintAttributes a,PrintAttributes b,android.os.CancellationSignal c,LayoutResultCallback cb,Bundle x){if(c.isCanceled()){cb.onLayoutCancelled();return;}cb.onLayoutFinished(new PrintDocumentInfo.Builder("Passport Photo").setContentType(PrintDocumentInfo.CONTENT_TYPE_PHOTO).setPageCount(1).build(),true);}public void onWrite(PageRange[] p,ParcelFileDescriptor fd,android.os.CancellationSignal c,WriteResultCallback cb){PdfDocument pdf=new PdfDocument();try{PdfDocument.Page page=pdf.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas cv=page.getCanvas();float mm=72f/25.4f,iw=req.widthMm*mm,ih=req.heightMm*mm;for(int row=0;row<5;row++)for(int col=0;col<4;col++){float x=18*mm+col*(iw+7*mm),y=18*mm+row*(ih+7*mm);if(x+iw<=cv.getWidth()&&y+ih<=cv.getHeight())cv.drawBitmap(result,null,new RectF(x,y,x+iw,y+ih),null);}pdf.finishPage(page);pdf.writeTo(new FileOutputStream(fd.getFileDescriptor()));cb.onWriteFinished(new PageRange[]{PageRange.ALL_PAGES});}catch(Exception e){cb.onWriteFailed(e.toString());}finally{pdf.close();try{fd.close();}catch(Exception ignored){}}}},new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).setColorMode(PrintAttributes.COLOR_MODE_COLOR).setResolution(new PrintAttributes.Resolution("passport","Passport Photo",300,300)).build());}
  void privacy(){new AlertDialog.Builder(this).setTitle("Privacy Policy").setMessage("Passport Photo ialah aplikasi pihak ketiga. Foto diproses secara lokal pada telefon untuk aliran asas. Foto tidak dijual dan tidak digunakan untuk latihan AI. Tiada upload ke server diperlukan untuk aliran asas. Pengguna mengawal penyimpanan dan pemadaman foto. Jika ciri cloud atau pihak ketiga ditambah, notis akan dikemas kini sebelum ciri itu digunakan.").setPositiveButton("Tutup",null).show();}
  void terms(){new AlertDialog.Builder(this).setTitle("Terma & Disclaimer").setMessage("Passport Photo bukan aplikasi rasmi Kerajaan Malaysia atau Jabatan Imigresen Malaysia. Aplikasi ini membantu menyediakan foto berdasarkan sumber rasmi yang dirujuk. Penerimaan akhir ditentukan oleh pihak berkuasa dan keperluan semasa. Spesifikasi boleh berubah. Pengguna bertanggungjawab memilih tujuan yang betul. Foto kekal milik pengguna.").setPositiveButton("Tutup",null).show();}
  void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
