package com.earnplayapps.passportphoto;

import android.app.Activity;import android.content.ClipData;import android.content.ClipboardManager;import android.content.Context;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.os.Bundle;import android.util.Base64;import android.view.View;import android.widget.*;import java.util.Locale;import java.util.UUID;

public class PaymentActivity extends Activity {
    private static final int QR_N=45;
    private static final String QR_B64="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+eo0r+AQXsbDQQC6HcaC6AXQDPhXQC6qwqK6AQTqDqQQD+qqqr+AADnzKAACqWhOokAWNSPQbwC7tCaqqALA2xpyQDaYo+7SABDU6ajAAOZayooABktr2aAAG/aSNMARini7ngDLP+mjyAOpZt4tgDPcej4yAOKuLOzQC31NjuEATlqO7ywBi5h5h2ABvmu7ggCuPi3zKALCe7SiACv3qyv2AAES4JEQD+MKK6oAQSR79FgC6lK+v6AXTP9S7gC62a4iaAQSdKypAD+96gwiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} TextView t(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(23,35,61));v.setPadding(0,dp(5),0,dp(5));return v;}
    @Override public void onCreate(Bundle b){super.onCreate(b);build();}
    String orderId(){android.content.SharedPreferences p=getSharedPreferences("passport_photo_order",0);String x=p.getString("order","");if(x.isEmpty()){x="PP-"+UUID.randomUUID().toString().replace("-","").substring(0,10).toUpperCase(Locale.US);p.edit().putString("order",x).apply();}return x;}
    void copy(String s){ClipboardManager cm=(ClipboardManager)getSystemService(Context.CLIPBOARD_SERVICE);cm.setPrimaryClip(ClipData.newPlainText("Passport Photo",s));Toast.makeText(this,"Disalin",Toast.LENGTH_SHORT).show();}
    private void build(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(24));root.setBackgroundColor(Color.rgb(245,247,251));root.addView(t("Passport Photo Pro",28));root.addView(t("RM19.90 • Lifetime • 1 device",17));root.addView(t("Bayar menggunakan Touch 'n Go eWallet",16));
        QRView qr=new QRView(this);root.addView(qr,new LinearLayout.LayoutParams(-1,dp(300)));root.addView(t("Scan QR di atas untuk bayaran. Jangan hantar kata laluan atau maklumat sensitif melalui chat.",14));
        String install=ProManager.installationId(this),order=orderId();root.addView(t("Installation ID (automatik)",13));TextView iv=t(install,13);root.addView(iv);Button ci=new Button(this);ci.setText("Copy Installation ID");ci.setOnClickListener(v->copy(install));root.addView(ci);root.addView(t("Order ID",13));TextView ov=t(order,15);root.addView(ov);Button co=new Button(this);co.setText("Copy Order ID");co.setOnClickListener(v->copy(order));root.addView(co);
        root.addView(t("Selepas bayaran manual disahkan, masukkan activation code yang diberikan.",14));EditText code=new EditText(this);code.setHint("Activation code");code.setSingleLine(true);root.addView(code);Button activate=new Button(this);activate.setText("ACTIVATE PRO");activate.setOnClickListener(v->{if(ProManager.activate(this,code.getText().toString())){Toast.makeText(this,"Pro activated",Toast.LENGTH_LONG).show();finish();}else Toast.makeText(this,"Invalid activation code",Toast.LENGTH_LONG).show();});root.addView(activate,new LinearLayout.LayoutParams(-1,dp(52)));Button paid=new Button(this);paid.setText("Saya Dah Bayar");paid.setOnClickListener(v->Toast.makeText(this,"Simpan Order ID dan tunggu activation code. Installation ID sudah dijana automatik.",Toast.LENGTH_LONG).show());root.addView(paid,new LinearLayout.LayoutParams(-1,dp(52)));Button back=new Button(this);back.setText("Back");back.setOnClickListener(v->finish());root.addView(back,new LinearLayout.LayoutParams(-1,dp(52)));sv.addView(root);setContentView(sv);
    }
    public static class QRView extends View{private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);private final byte[] bytes;QRView(Context c){super(c);bytes=Base64.decode(QR_B64,Base64.DEFAULT);p.setColor(Color.rgb(233,30,99));setBackgroundColor(Color.WHITE);}private boolean dark(int i){int bi=i>>3,bit=7-(i&7);return bi<bytes.length&&((bytes[bi]>>bit)&1)==1;}@Override protected void onDraw(Canvas c){super.onDraw(c);float side=Math.min(getWidth(),getHeight()),cell=side/QR_N,left=(getWidth()-side)/2f,top=(getHeight()-side)/2f;for(int y=0;y<QR_N;y++)for(int x=0;x<QR_N;x++)if(dark(y*QR_N+x))c.drawRect(left+x*cell,top+y*cell,left+(x+1)*cell+.4f,top+(y+1)*cell+.4f,p);}}
}
