package com.earnplayapps.passportphoto;

import android.app.Activity;import android.content.ContentValues;import android.graphics.Bitmap;import android.graphics.BitmapFactory;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.net.Uri;import android.os.Bundle;import android.provider.MediaStore;import android.widget.*;import java.io.*;

public class PrintStudioActivity extends Activity{
 Bitmap source;ImageView preview;int count=6;String paper="A4";Bitmap sheet;int widthMm=0,heightMm=0;boolean exactFit=true;int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setMinHeight(dp(48));return x;}
 @Override public void onCreate(Bundle b){super.onCreate(b);String path=getIntent().getStringExtra("bitmap_path");source=BitmapFactory.decodeFile(path);widthMm=getIntent().getIntExtra("width_mm",0);heightMm=getIntent().getIntExtra("height_mm",0);if(source==null){finish();return;}build();}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(16));root.setBackgroundColor(Color.rgb(245,247,251));TextView t=new TextView(this);t.setText("Print Studio");t.setTextSize(25);t.setTextColor(Color.rgb(23,35,61));root.addView(t);TextView i=new TextView(this);i.setText((widthMm>0&&heightMm>0?"Photo: "+widthMm+" × "+heightMm+" mm":"Photo: custom/source proportion")+" • 300 DPI print layout");i.setTextColor(Color.rgb(91,100,117));root.addView(i);LinearLayout papers=new LinearLayout(this);Button a4=b("A4");Button p46=b("4×6");a4.setOnClickListener(v->{paper="A4";render();});p46.setOnClickListener(v->{paper="4×6";render();});papers.addView(a4,new LinearLayout.LayoutParams(0,dp(48),1));papers.addView(p46,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(papers);preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);root.addView(preview,new LinearLayout.LayoutParams(-1,0,1));HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout row=new LinearLayout(this);for(int n:new int[]{2,4,6,8,10,12}){Button q=b(""+n);q.setOnClickListener(v->{count=Integer.parseInt(((Button)v).getText().toString());render();});row.addView(q,new LinearLayout.LayoutParams(dp(64),dp(48)));}hs.addView(row);root.addView(hs);Button save=b("SAVE PRINT SHEET");save.setOnClickListener(v->save());root.addView(save,new LinearLayout.LayoutParams(-1,dp(54)));Button back=b("Back");back.setOnClickListener(v->finish());root.addView(back);render();setContentView(root);}
 int px(float mm){return Math.max(1,Math.round(mm*300f/25.4f));}
 void render(){int w=paper.equals("4×6")?1200:2480,h=paper.equals("4×6")?1800:3508;sheet=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(sheet);c.drawColor(Color.WHITE);int photoW=widthMm>0?px(widthMm):0,photoH=heightMm>0?px(heightMm):0;int cols=count<=4?2:3;int rows=(count+cols-1)/cols;int margin=36,gap=24;Paint line=new Paint();line.setColor(Color.LTGRAY);line.setStyle(Paint.Style.STROKE);line.setStrokeWidth(2);exactFit=true;for(int n=0;n<count;n++){int col=n%cols,row=n/cols;float x,y,pw,ph;if(photoW>0&&photoH>0){pw=photoW;ph=photoH;float totalW=cols*pw+(cols-1)*gap,totalH=rows*ph+(rows-1)*gap;if(totalW>w-2*margin||totalH>h-2*margin){exactFit=false;pw=photoW;ph=photoH;x=(w-totalW)/2f+col*(pw+gap);y=(h-totalH)/2f+row*(ph+gap);}else{x=(w-totalW)/2f+col*(pw+gap);y=(h-totalH)/2f+row*(ph+gap);}}else{float cellW=(w-gap*(cols+1))/(float)cols,cellH=(h-gap*(rows+1))/(float)rows;float scale=Math.min((cellW-20)/(float)source.getWidth(),(cellH-20)/(float)source.getHeight());pw=Math.max(1,Math.round(source.getWidth()*scale));ph=Math.max(1,Math.round(source.getHeight()*scale));x=gap+col*(cellW+gap)+(cellW-pw)/2f;y=gap+row*(cellH+gap)+(cellH-ph)/2f;}if(exactFit||photoW==0){Bitmap p=Bitmap.createScaledBitmap(source,Math.max(1,Math.round(pw)),Math.max(1,Math.round(ph)),true);c.drawBitmap(p,x,y,null);}c.drawRect(x,y,x+pw,y+ph,line);}preview.setImageBitmap(sheet);}
 void save(){if(widthMm>0&&heightMm>0&&!exactFit){new AlertDialog.Builder(this).setTitle("Photo size cannot fit").setMessage("The selected quantity cannot fit on "+paper+" while preserving the official "+widthMm+" × "+heightMm+" mm photo size. Reduce the quantity or choose another paper size.").setPositiveButton("OK",null).show();return;}try{String name="PassportPhoto_"+paper.replace("×","x")+"_"+count+"_"+System.currentTimeMillis()+".jpg";if(android.os.Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,name);v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Passport Photo");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(u==null)throw new IOException("MediaStore insert failed");OutputStream o=getContentResolver().openOutputStream(u);if(o==null)throw new IOException("Output stream failed");sheet.compress(Bitmap.CompressFormat.JPEG,95,o);o.close();}else{File d=new File(getExternalFilesDir(null),"Passport Photo");d.mkdirs();File f=new File(d,name);FileOutputStream o=new FileOutputStream(f);sheet.compress(Bitmap.CompressFormat.JPEG,95,o);o.close();}Toast.makeText(this,"Print sheet disimpan"+(widthMm>0?" • saiz foto dikekalkan "+widthMm+"×"+heightMm+" mm":""),Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Gagal simpan: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
}
