package com.earnplayapps.passportphoto;

import android.app.Activity;import android.graphics.Bitmap;import android.graphics.Canvas;import android.graphics.Color;import android.os.Bundle;import android.widget.*;import java.io.*;

public class PrintStudioActivity extends Activity{
 Bitmap source;ImageView preview;int count=6;int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);return x;}
 @Override public void onCreate(Bundle b){super.onCreate(b);String path=getIntent().getStringExtra("bitmap_path");source=android.graphics.BitmapFactory.decodeFile(path);if(source==null){finish();return;}build();}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(16));root.setBackgroundColor(Color.rgb(245,247,251));TextView t=new TextView(this);t.setText("Print Studio");t.setTextSize(25);root.addView(t);TextView i=new TextView(this);i.setText("A4 • 2 / 4 / 6 / 8 / 10 / 12 photos");root.addView(i);preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);root.addView(preview,new LinearLayout.LayoutParams(-1,0,1));LinearLayout row=new LinearLayout(this);for(int n:new int[]{2,4,6,8,10,12}){Button q=b(""+n);q.setOnClickListener(v->{count=Integer.parseInt(((Button)v).getText().toString());render();});row.addView(q,new LinearLayout.LayoutParams(0,dp(48),1));}root.addView(row);Button save=b("SAVE A4 PRINT SHEET");save.setOnClickListener(v->save());root.addView(save,new LinearLayout.LayoutParams(-1,dp(54)));render();setContentView(root);}
 void render(){int w=1240,h=1754;Bitmap sheet=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(sheet);c.drawColor(Color.WHITE);int cols=2,rows=(count+1)/2;int cellW=w/cols,cellH=h/rows;for(int n=0;n<count;n++){int col=n%cols,row=n/cols;Bitmap p=Bitmap.createScaledBitmap(source,Math.max(1,cellW-40),Math.max(1,cellH-40),true);c.drawBitmap(p,20+col*cellW,20+row*cellH,null);}preview.setImageBitmap(sheet);preview.setTag(sheet);}
 void save(){try{Bitmap s=(Bitmap)preview.getTag();File d=new File(getExternalFilesDir(null),"Passport Photo");d.mkdirs();File f=new File(d,"passport_print_A4_"+System.currentTimeMillis()+".jpg");FileOutputStream o=new FileOutputStream(f);s.compress(Bitmap.CompressFormat.JPEG,95,o);o.close();Toast.makeText(this,"Print sheet disimpan",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Gagal simpan",Toast.LENGTH_LONG).show();}}
}
