package com.earnplayapps.passportphoto;

import android.app.Activity;import android.content.ContentValues;import android.graphics.Bitmap;import android.graphics.BitmapFactory;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.net.Uri;import android.os.Bundle;import android.provider.MediaStore;import android.widget.*;import java.io.*;

public class PrintStudioActivity extends Activity{
 Bitmap source;ImageView preview;int count=6;String paper="A4";Bitmap sheet;int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setMinHeight(dp(48));return x;}
 @Override public void onCreate(Bundle b){super.onCreate(b);String path=getIntent().getStringExtra("bitmap_path");source=BitmapFactory.decodeFile(path);if(source==null){finish();return;}build();}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(16));root.setBackgroundColor(Color.rgb(245,247,251));TextView t=new TextView(this);t.setText("Print Studio");t.setTextSize(25);t.setTextColor(Color.rgb(23,35,61));root.addView(t);TextView i=new TextView(this);i.setText("Paper: A4 • 4×6   |   Photo proportion is preserved");i.setTextColor(Color.rgb(91,100,117));root.addView(i);LinearLayout papers=new LinearLayout(this);Button a4=b("A4");Button p46=b("4×6");a4.setOnClickListener(v->{paper="A4";render();});p46.setOnClickListener(v->{paper="4×6";render();});papers.addView(a4,new LinearLayout.LayoutParams(0,dp(48),1));papers.addView(p46,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(papers);preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);root.addView(preview,new LinearLayout.LayoutParams(-1,0,1));HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout row=new LinearLayout(this);for(int n:new int[]{2,4,6,8,10,12}){Button q=b(""+n);q.setOnClickListener(v->{count=Integer.parseInt(((Button)v).getText().toString());render();});row.addView(q,new LinearLayout.LayoutParams(dp(64),dp(48)));}hs.addView(row);root.addView(hs);Button save=b("SAVE PRINT SHEET");save.setOnClickListener(v->save());root.addView(save,new LinearLayout.LayoutParams(-1,dp(54)));Button back=b("Back");back.setOnClickListener(v->finish());root.addView(back);render();setContentView(root);}
 void render(){int w=paper.equals("4×6")?1200:1240,h=paper.equals("4×6")?1800:1754;sheet=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(sheet);c.drawColor(Color.WHITE);int cols=count<=4?2:3;int rows=(count+cols-1)/cols;int gap=24;int cellW=(w-gap*(cols+1))/cols,cellH=(h-gap*(rows+1))/rows;Paint line=new Paint();line.setColor(Color.LTGRAY);line.setStyle(Paint.Style.STROKE);line.setStrokeWidth(2);for(int n=0;n<count;n++){int col=n%cols,row=n/cols;float left=gap+col*(cellW+gap),top=gap+row*(cellH+gap);float scale=Math.min((cellW-20)/(float)source.getWidth(),(cellH-20)/(float)source.getHeight());int pw=Math.max(1,Math.round(source.getWidth()*scale)),ph=Math.max(1,Math.round(source.getHeight()*scale));Bitmap p=Bitmap.createScaledBitmap(source,pw,ph,true);float x=left+(cellW-pw)/2f,y=top+(cellH-ph)/2f;c.drawBitmap(p,x,y,null);c.drawRect(left,top,left+cellW,top+cellH,line);}preview.setImageBitmap(sheet);}
 void save(){try{String name="PassportPhoto_"+paper.replace("×","x")+"_"+count+"_"+System.currentTimeMillis()+".jpg";if(android.os.Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,name);v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Passport Photo");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(u==null)throw new IOException("MediaStore insert failed");OutputStream o=getContentResolver().openOutputStream(u);if(o==null)throw new IOException("Output stream failed");sheet.compress(Bitmap.CompressFormat.JPEG,95,o);o.close();}else{File d=new File(getExternalFilesDir(null),"Passport Photo");d.mkdirs();File f=new File(d,name);FileOutputStream o=new FileOutputStream(f);sheet.compress(Bitmap.CompressFormat.JPEG,95,o);o.close();}Toast.makeText(this,"Print sheet disimpan",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Gagal simpan: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
}
